name: Deploy to Nance server
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.SERVER_SECRET}}
          host: ${{secrets.SERVER_HOSTNAME}}
          username: ${{secrets.SERVER_USER}}
          port: 22
          script: |
            cd /works/bot/mocho
            git pull origin master
            supervisorctl restart Mocho
